package com.cicl.system.CICLIT_SYSTEM;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class HR_Emp_Details_OK_Cancel extends AbsoluteLayout {
	protected Button button_OK;
	protected Button button_CANCEL;
	protected Label label_CONFIRM;

	public HR_Emp_Details_OK_Cancel() {
		Design.read(this);
	}
}
