package com.cicl.system.CICLIT_SYSTEM;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class HR_Emp_Personal_Details extends AbsoluteLayout {
	protected TabSheet tab1_per_det;
	protected Panel panel;
	protected AbsoluteLayout absoluteLayout;
	protected Button button_srch;
	protected TextField textField_epf;
	protected TextArea textArea_padress;
	protected TextField textField_pcity;
	protected TextField textField_pstate;
	protected TextField textField_pzip;
	protected TextArea textArea_taddress;
	protected TextField textField_tstate;
	protected TextField textField_tcity;
	protected TextField textField_tzip;
	protected TextField textField_homePhone;
	protected TextField textField_alterPhone;
	protected TextField textField_email;
	protected ComboBox comboBox_mart_status;
	protected TextField textField_spouseName;
	protected TextField textField_spousEmp;
	protected TextField textField_spousePhone1;
	protected TextField textField_spousePhone;
	protected AbsoluteLayout absoluteLayout1;
	protected TextField textField_fName;
	protected TextField textField_fOccup;
	protected TextField textField_w_f_Pno;
	protected TextField textField_f_workloc;
	protected TextField textField_mName;
	protected TextField textField_m_occup;
	protected TextField textField__m_pno;
	protected TextField textField_m_wLoc;
	protected TextField textField_sib21;
	protected TextField textField_occ_sib1;
	protected TextField textField_wpno_s1;
	protected TextField textField_sib2;
	protected TextField textField_sib2_occup;
	protected TextField textField_sib2_wpno;
	protected TextField textField_sib3;
	protected TextField textField_occ_s3;
	protected TextField textField_sib3_wpno;
	protected TextField textField_sib4;
	protected TextField textField_occ_sib4;
	protected TextField textField4_sib3_wpno;
	protected AbsoluteLayout absoluteLayout2;
	protected TextField textField_emg1Fullnme;
	protected TextArea textArea_emg1PAddress;
	protected TextField textField_emg1_city;
	protected TextField textField_emg1_state;
	protected TextField textField_emg1_zip;
	protected TextField textField_emg1_hpno;
	protected TextField textField_emg1_alterpNo;
	protected TextField textField_emg1_reltion;
	protected TextField textField_emg2_fullName;
	protected TextArea textArea_emg2_paddress;
	protected TextField textField_emg2_city1;
	protected TextField textField_emg2_state;
	protected TextField textField_emg2_zip;
	protected TextField textField_emg2_hPno;
	protected TextField textField_emg2_relation;
	protected Button btn_submit;
	protected Button btn_update;

	public HR_Emp_Personal_Details() {
		Design.read(this);
	}
}
